### ISSUE TITLE
What companies\projects use Izanami?

### ISSUE THREAD

**Issue by yuriron** [MAIF/izanami#240]
I run POC for Izanami Java and React clients. I like the product so far. I'd like to know if anyone uses it in production.

**Comment by larousso** [comment]
Hi, we're using it at maif in production. As far as l know it is also used at Kiabi and ovh and I met other people during conference that were using it to.

**Comment by sorenvalentinjp** [comment]
Danish newspapers Jyllands-Posten, finans and watchmedier are using it in production.

**Comment by cwoodrow** [comment]
> Danish newspapers Jyllands-Posten, finans and watchmedier are using it in production.

Cool :D any feedbacks ?

**Comment by sorenvalentinjp** [comment]
Sure. So far we are only using the feature flag part of it in our Scala + Play framework applications. The izanami scala client is solid and seems very idiomatic to the scala environment. The izanami server is hosted on AWS ECS with a redis as the database. This combination has not crashed so far and responds very fast. 
The pattern system that izanami uses to restrict features/users etc. can seem a bit unintuitive at times, but it is a powerful tool that does the job. We use it to restrict users to specific feature patterns so that several teams can share the same izanami server without bothering each other.
We love the fact that there are different modes in the izanami client, the dev mode is very useful for developing locally, because we dont want to spin up an izanami server in our development environment.
The documentation is decent and there are example projects, which are helpful for getting started.
