### ISSUE TITLE
Support for logging in JSON

### ISSUE THREAD

**Issue by SoerenSilkjaer** [MAIF/izanami#485]
A lot of logging infrastructure does not play well with the typical console logger. It would be nice if one could configure the izanami server to log in JSON.

**Comment by larousso** [comment]
Hi, the lib `logstash-logback-encoder` is on the classpath, so you could specify a logback.xml file with the correct appender to log in json

**Comment by SoerenSilkjaer** [comment]
> Hi, the lib `logstash-logback-encoder` is on the classpath, so you could specify a logback.xml file with the correct appender to log in json

Thanks. I will try that. Are you planning on making it a configaration flag or something?

**Comment by larousso** [comment]
Hi, it is not configurable due to playframework but if you're using docker, you can pass java system properties this way : 

`docker run -it -p 9001:9001 maif/izanami -Dhttp.port=9001 -Dlogger.file=conf/prod-logger.xml` 

If your logback config is accessible from your docker instance, this command should work.
