### ISSUE TITLE
Add more information for healthcheck

### ISSUE THREAD

**Issue by yacine-1** [MAIF/izanami#662]
It took me a long time to detect that the database connection was broken while frontend was working fine and the argocd deployment was healthy.

As mentioned in #153, I need a health endpoint to check if the backend and the database connection are ok (and optionally the version tag) without authentication.

When connected, api/_health endpoint returns "{}" but this information is not enough.

The documentation is not clear about this...

**Comment by ptitFicus** [comment]
Hi @sipr-invivo, it's not yet, however I will take care of it next week !

**Comment by ptitFicus** [comment]
Hi,

I just released 2.4.2 that provides database health status information in health endpoint.

I didn't update swagger yet (I forgot :s), however the idea is that the "database" field from response payload is true while database is reachable, and false otherwise. Morever endpoint will return 500 if database is not healthy.

Let me know if you need anything else !

Best regards
