### ISSUE TITLE
make scopes configurable in V2

### ISSUE THREAD

**Issue by keltakmaster** [MAIF/izanami#827]
Hi!

Would it be possible to make openid scopes configurable for izanami v2?

Right now, scopes are hardcoded as "scope=openid%20profile%20email%20name".

Passing the "name" scope in unusual as it is not part of the openID standards, it's a claim usually available in the "profile" scope.

As a result, users must define a new scope "name" in their OIDC provider.

**Comment by ptitFicus** [comment]
Hi,

Thanks for the issue, I'll look into it, but I don't think it'll be an issue to make this configurable.

**Comment by ptitFicus** [comment]
Hi @keltakmaster,

This should be fixed in 2.2.0, that was released just now.

Scopes are now configurable, moreover you can specify which element of the id token will be used as username and email on izanami's side.

[More details here](https://maif.github.io/izanami/docs/guides/configuration#openid) please let me know if you are missing something else on OIDC.

**Comment by keltakmaster** [comment]
That's very kind of you! I will try that tomorrow and let you know if everything is OK !

**Comment by keltakmaster** [comment]
Hi @ptitFicus,

Everything works as intended regarding OIDC, many thanks!
